# netlify.toml — Aikya (Netlify subdomain)

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Use Node 20 for @supabase/supabase-js
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"

# Functions runtime settings (used by scheduled function too)
[functions]
  node_bundler = "esbuild"
  included_files = []

# ---- Scheduled Functions ----
# Runs the embeddings backfill every 20 minutes.
# Make sure you have netlify/functions/embeddings-cron.ts in your repo.
[[scheduled.functions]]
  name = "embeddings-cron"
  cron = "*/20 * * * *"

# -----------------------------
# Security headers (safe defaults + Supabase/Google auth allowance)
[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'unsafe-inline' https://plausible.io https://apis.google.com https://accounts.google.com;
    style-src 'self' 'unsafe-inline';
    img-src 'self' data: https:;
    font-src 'self' data:;
    connect-src 'self' https://plausible.io https://*.supabase.co wss://*.supabase.co;
    frame-src https://www.youtube-nocookie.com https://*.supabase.co https://accounts.google.com;
    base-uri 'self';
    form-action 'self'
  """
  Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
  Referrer-Policy = "strict-origin-when-cross-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"

# Cache Next.js build assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Cache files under /public (optional)
[[headers]]
  for = "/public/*"
  [headers.values]
  Cache-Control = "public, max-age=604800"
