# netlify.toml — Aikya (production-ready)

[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.20.3"
  # Helps avoid peer-deps install hiccups on fresh builds
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"

# --- Security headers for all routes ---
[[headers]]
  for = "/*"
  [headers.values]
  # If you don't use Plausible, remove https://plausible.io from script-src & connect-src
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://plausible.io; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://plausible.io; frame-src https://www.youtube-nocookie.com; base-uri 'self'; form-action 'self'"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
  Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# --- Cache static assets aggressively ---
[[headers]]
  for = "/_next/static/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# --- Optional: cache /public assets (edit paths if needed) ---
[[headers]]
  for = "/public/*"
  [headers.values]
  Cache-Control = "public, max-age=604800"

# --- Optional: redirect www → apex (edit YOUR-DOMAIN if you set a custom domain) ---
[[redirects]]
  from = "https://aikyanow.netlify.app/*"
  to = "https://YOUR-DOMAIN.com/:splat"
  status = 301
  force = true
